; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "PythonPAM"
!define PRODUCT_VERSION "1.0.5"
!define PRODUCT_PUBLISHER "ARGOS LABS"
; !define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\AppMainExe.exe"
; !define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
; !define PRODUCT_UNINST_ROOT_KEY "HKLM"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Binary
!define BINARY_PATH "python_pam"

; Page license 
; Page components
; Page directory
; Page instfiles
; UninstPage uninstConfirm
; UninstPage instfiles

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
!insertmacro MUI_PAGE_LICENSE "..\..\README.txt"
; Directory page
!insertmacro MUI_PAGE_DIRECTORY

!insertmacro MUI_PAGE_COMPONENTS

; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\AppMainExe.exe"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
InstallDir "$LOCALAPPDATA\PythonPAM"
; InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
XPStyle on
ShowInstDetails show
ShowUnInstDetails show



!include NSIS.PythonPAM32.nsi




; Section "MainSection" SEC01
;   SetOutPath "$INSTDIR"
;   SetOverwrite ifnewer
;   File "c:\path\to\file\AppMainExe.exe"
;   CreateDirectory "$SMPROGRAMS\PythonPAM"
;   CreateShortCut "$SMPROGRAMS\PythonPAM\PythonPAM.lnk" "$INSTDIR\AppMainExe.exe"
;   CreateShortCut "$DESKTOP\PythonPAM.lnk" "$INSTDIR\AppMainExe.exe"
;   File "c:\path\to\file\Example.file"
; SectionEnd

; Section -AdditionalIcons
;   CreateShortCut "$SMPROGRAMS\PythonPAM\Uninstall.lnk" "$INSTDIR\uninst.exe"
; SectionEnd

; Section -Post
;   WriteUninstaller "$INSTDIR\uninst.exe"
;   WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\AppMainExe.exe"
;   WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
;   WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
;   WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\AppMainExe.exe"
;   WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
;   WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
; SectionEnd


; Function un.onUninstSuccess
;   HideWindow
;   MessageBox MB_ICONINFORMATION|MB_OK "$(^Name)��(��) ������ ���ŵǾ����ϴ�."
; FunctionEnd

; Function un.onInit
;   MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "$(^Name)��(��) �����Ͻðڽ��ϱ�?" IDYES +2
;   Abort
; FunctionEnd

; Section Uninstall
;   Delete "$INSTDIR\uninst.exe"
;   Delete "$INSTDIR\Example.file"
;   Delete "$INSTDIR\AppMainExe.exe"

;   Delete "$SMPROGRAMS\PythonPAM\Uninstall.lnk"
;   Delete "$DESKTOP\PythonPAM.lnk"
;   Delete "$SMPROGRAMS\PythonPAM\PythonPAM.lnk"

;   RMDir "$SMPROGRAMS\PythonPAM"
;   RMDir "$INSTDIR"

;   DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
;   DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
;   SetAutoClose true
; SectionEnd